print('Hello World Assalomu alaykum!')
print('Hi guys')
print("Men \"Lenovo\" markazidagi kpmpyuter ishlataman" )
print("Men 'IPhone' markazidagi telefon ishlataman")
print('Men \'IPhone \'  markazidagi telefon ishlataman')
print("Odami ersang, demagil odami,\nOniki, yo'q xalq g'amidin g'ami")
# Arifmetik amallar
print(5 +6)
print(10 - 4)
print(12 * 3)
print(15 / 5, 12 * 5, 52 + 12, 65 - 15)
print(15 // 7)
print(65 // 5)
print(5 ** 4, 12 ** 2)
print(64 ** (1 / 2))
print(625 ** (1 / 4))
print(12 % 5)
print(4 % 7) #4
print(5 % 6) #5
print( "Beshning kvadrati",5 ** 2, "ga teng")
print('3x3=',3*3)
# Amaliyot
print("\"Nexia\", \"Tico\", 'Damas' ko'rganlar qilar havas")
print('"Nexia", "Tico", \'Damas\' ko\'srganlar qilar havas')
print( "5 ning 4-darajasi",5 ** 4)
print("22 ni 4ga bolganda",22 % 4, 'qoladi qoladi')
print("tomonlari 125 bolgan kvadrat peremeti",125 * 4, 'yuzi esa',125 * 125)
print("diametri 12 bolgan doiraning yuzi",3.14*(12/2)**2)
print("Geron formulalari:  \(A=\sqrt{s(s-a)(s-b)(s-c)}\)")
print("Katetlari 6 va 7 bolgan togri burchakli uchburchakning gipotenuzasi", (6**2+7**2)**(1/2))    
print( "Tomonlari 3, 4, 5 ga teng bo'lgan uchburchaking yuzasi",(6 * (6 - 3) * (6 -5) * (6 - 4)) ** (1/2), "ga teng")